source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'couchbase-lite-ios'
pod 'ArcGIS-Runtime-SDK-iOS'
pod 'BEMSimpleLineGraph'
