# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "Precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.provision :shell, :path => "setup.sh"
  config.vm.synced_folder ".", "/home/vagrant/raceday"
  config.vm.network "private_network", ip: "192.168.70.5"
  config.vm.network "forwarded_port", guest: 5000, host: 8875
end
